packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  esbuild: true
  prisma: true

patchedDependencies:
  '@langchain/langgraph-api@1.4.3': patches/@langchain__langgraph-api@1.4.3.patch
