/** 制作交付物校验：出稿 / 完成执行 / 质检共用 */
import type { ProductionDepartment, WorkPreview } from "@yougan/domain";

import {
  getPreview,
  getProductionPlan,
} from "#agent/state-io/index.js";
import type { AgentStateType } from "#agent/state.js";

const MIN_WRITING_BODY_LENGTH = 20;

const WRITING_FAILURE_MARKERS = [
  "文案生成失败，请重试。",
  "暂时无法完成该任务，请稍后重试。",
] as const;

export function isPlaceholderDeliverableText(text: string): boolean {
  const trimmed = text.trim();
  if (!trimmed) return true;
  return WRITING_FAILURE_MARKERS.some((marker) => trimmed.includes(marker));
}

export function isValidWritingDeliverable(
  preview: WorkPreview | null | undefined,
): boolean {
  const body = preview?.body?.trim() ?? "";
  if (body.length < MIN_WRITING_BODY_LENGTH) return false;
  return !isPlaceholderDeliverableText(body);
}

export function hasDepartmentDeliverable(
  preview: WorkPreview | null | undefined,
  department: ProductionDepartment,
): boolean {
  if (department === "writing") {
    return isValidWritingDeliverable(preview);
  }
  const notes = preview?.notes?.trim() ?? "";
  if (!notes) return false;
  return notes.includes(`（${department}）`);
}

export function pendingDepartments(
  tasks: Array<{ department?: ProductionDepartment }>,
): ProductionDepartment[] {
  const depts = tasks.map((t) => t.department ?? "writing");
  return [...new Set(depts)];
}

export function missingDeliverableDepartments(
  preview: WorkPreview | null | undefined,
  tasks: Array<{ department?: ProductionDepartment }>,
): ProductionDepartment[] {
  return pendingDepartments(tasks).filter(
    (dept) => !hasDepartmentDeliverable(preview, dept),
  );
}

export function formatMissingDeliverableMessage(
  departments: ProductionDepartment[],
): string {
  const labels: Record<ProductionDepartment, string> = {
    writing: "文案正文",
    design: "设计交付物",
    audio: "音频交付物",
    video: "视频交付物",
  };
  const parts = departments.map((d) => labels[d]);
  return `执行完成被阻止：尚缺 ${parts.join("、")}。请先调用 generate_draft 或 spawn_specialist 产出交付物后再 complete_execution。`;
}

export function canAutoGenerateDraft(state: AgentStateType): boolean {
  const plan = getProductionPlan(state);
  if (!plan.pending_tasks.length) {
    return false;
  }
  const needsWriting = plan.pending_tasks.some(
    (t) => (t.department ?? "writing") === "writing",
  );
  if (!needsWriting) return false;
  return !isValidWritingDeliverable(getPreview(state));
}

export function canAutoSpawnDesign(state: AgentStateType): boolean {
  const plan = getProductionPlan(state);
  const designTask = plan.pending_tasks.find((t) => t.department === "design");
  if (!designTask) return false;
  return !hasDepartmentDeliverable(getPreview(state), "design");
}
