/** directWriting 之后：有 tool_calls 则执行工具；否则按需自动出稿 */
import { AIMessage } from "@langchain/core/messages";
import { END } from "@langchain/langgraph";

import type { AgentStateType } from "#agent/state.js";

import { canAutoGenerateDraft } from "../helpers/deliverable.js";

export const from = "directWriting" as const;

export type AfterDirectWritingTarget =
  | "runProductionTools"
  | "generateDraft"
  | typeof END;

function lastAiHasToolCalls(state: AgentStateType): boolean {
  const last = state.messages?.at(-1);
  return (
    AIMessage.isInstance(last) && (last.tool_calls?.length ?? 0) > 0
  );
}

export function selectAfterDirectWriting(
  state: AgentStateType,
): AfterDirectWritingTarget {
  if (lastAiHasToolCalls(state)) return "runProductionTools";
  if (canAutoGenerateDraft(state)) return "generateDraft";
  return END;
}

export const paths = {
  runProductionTools: "runProductionTools",
  generateDraft: "generateDraft",
  __end__: END,
} as const;
