/** runProductionTools 之后：按 staging 待办路由 work 节点或回创作者 */
import { getProductionStagingMeta } from "#agent/state-io/index.js";
import type { AgentStateType } from "#agent/state.js";

import {
  canAutoGenerateDraft,
  canAutoSpawnDesign,
} from "../helpers/deliverable.js";

export const from = "runProductionTools" as const;

export type AfterRunProductionToolsTarget =
  | "directWriting"
  | "directDesign"
  | "generateDraft"
  | "spawnSpecialist"
  | "inspectDeliverable";

export function selectAfterRunProductionTools(
  state: AgentStateType,
): AfterRunProductionToolsTarget {
  const meta = getProductionStagingMeta(state);
  if (meta?.pendingInspect) {
    return "inspectDeliverable";
  }
  if (meta?.pendingGenerateDraft) {
    return "generateDraft";
  }
  if (meta?.pendingSpawnSpecialist) {
    return "spawnSpecialist";
  }
  if (canAutoGenerateDraft(state)) {
    return "generateDraft";
  }
  if (canAutoSpawnDesign(state)) {
    return "spawnSpecialist";
  }
  if (meta?.inspectPipeline === "design") {
    return "directDesign";
  }
  return "directWriting";
}

export const paths: AfterRunProductionToolsTarget[] = [
  "directWriting",
  "directDesign",
  "generateDraft",
  "spawnSpecialist",
  "inspectDeliverable",
];
