/** toolNode：按 staging 待办进入 work 节点或回创作者 */
import { getProductionStagingMeta } from "#agent/state-io/index.js";
import type { AgentStateType } from "#agent/state.js";

import {
  canAutoGenerateDraft,
  canAutoSpawnDesign,
} from "../helpers/deliverable.js";

export const from = "toolNode" as const;

export type PendingProductionWorkTarget =
  | "llmCall"
  | "designLlmCall"
  | "generateDraft"
  | "spawnSpecialist"
  | "inspectProduction";

export function dispatchPendingProductionWork(
  state: AgentStateType,
): PendingProductionWorkTarget {
  const meta = getProductionStagingMeta(state);
  if (meta?.pendingInspect) {
    return "inspectProduction";
  }
  if (meta?.pendingGenerateDraft) {
    return "generateDraft";
  }
  if (meta?.pendingSpawnSpecialist) {
    return "spawnSpecialist";
  }
  if (canAutoGenerateDraft(state)) {
    return "generateDraft";
  }
  if (canAutoSpawnDesign(state)) {
    return "spawnSpecialist";
  }
  if (meta?.inspectPipeline === "design") {
    return "designLlmCall";
  }
  return "llmCall";
}

export const paths: PendingProductionWorkTarget[] = [
  "llmCall",
  "designLlmCall",
  "generateDraft",
  "spawnSpecialist",
  "inspectProduction",
];
