/** llmCall / designLlmCall：有 tool_calls 则进 toolNode；否则按需自动出稿 */
import { AIMessage } from "@langchain/core/messages";
import { END } from "@langchain/langgraph";

import type { AgentStateType } from "#agent/state.js";

import {
  canAutoGenerateDraft,
  canAutoSpawnDesign,
} from "../helpers/deliverable.js";

export const fromLlm = "llmCall" as const;
export const fromDesign = "designLlmCall" as const;

export type LlmCallTarget =
  | "toolNode"
  | "generateDraft"
  | "spawnSpecialist"
  | typeof END;

function lastAiHasToolCalls(state: AgentStateType): boolean {
  const last = state.messages?.at(-1);
  return (
    AIMessage.isInstance(last) && (last.tool_calls?.length ?? 0) > 0
  );
}

export function routeLlmCall(state: AgentStateType): LlmCallTarget {
  if (lastAiHasToolCalls(state)) return "toolNode";
  if (canAutoGenerateDraft(state)) return "generateDraft";
  return END;
}

export function routeDesignLlmCall(state: AgentStateType): LlmCallTarget {
  if (lastAiHasToolCalls(state)) return "toolNode";
  if (canAutoSpawnDesign(state)) return "spawnSpecialist";
  return END;
}

export const llmPaths = {
  toolNode: "toolNode",
  generateDraft: "generateDraft",
  __end__: END,
} as const;

export const designPaths = {
  toolNode: "toolNode",
  spawnSpecialist: "spawnSpecialist",
  __end__: END,
} as const;
